export const anims = {
    start: [
        {type: 'intro', view: 'intro', title:'Beef', location: 'beef', subSection: 'intro', overlay: {start: [10, 11], end: [13, 15]}},
        {type: 'intro', view: 'intro', title:'Potatoes', location: 'potatoes', subSection: 'intro', overlay: {start: [12, 13], end: [23, 27]}},
        {type: 'intro', view: 'intro', title:'Honey', location: 'honey', subSection: 'intro', overlay: {start: [18, 19], end: [22, 28]}},
        {type: 'intro', view: 'intro', title:'Milk', location: 'milk', subSection: 'intro', overlay: {start: [16, 17], end: [22, ]}},
        {type: 'intro', view: 'intro', title:'Sunflowers', location: 'sunflowers', subSection: 'intro', overlay: {start: [14, 15], end: [22, 24]}},
    ],
    honey: {
        numberOfStops: 3,
        intro: {
            title: 'Honey Glaze',
            type: 'intro',
            view: 'intro',
            navButtons: [
                {type: 'btp', view: 'home', title:'Plate'},
                {type: 'animation', view: 'map', title:'Honey Glaze', location: 'honey', subSection: 'plateToBoxes'},
            ],
            internalButtons: [{}],
            location: 'honey',
            disableNavButtons: true,
            shouldLoop: false,
            post: {
                time_start: 0,
                time_end: 10,
                shouldLoop: true,
            }
        },
        plateToBoxes: {
            type: 'animation',
            location: 'honey',
            time_start: 60.5,
            time_end: 66,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'boxes',
        },
        boxes: {
            description: 'Bees fly freely to pollinate nearby plants and collect nectar and pollen, which they return to their hives called “bee boxes”.  Bee boxes are designed to allow the beekeeper to harvest the honey without disrupting the hive, which is deposited by bees in the waxy honeycomb. In our case, the beekeeper has arrangements with other farmers to keep hives on the edges of their property, giving the bees diversity of nutrition and the farmer the useful  pollinating activity the bees provide. During the foraging season, each worker bee lives for approximately 6 weeks, and deposits just 1/10th of a teaspoon of honey in her lifetime!',
            stepNumber: 1,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/honey-jpgs/honey-beeboxes-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Honey/Bee+Boxes.mp4',
            location: 'honey',
            nextTitle: 'Proccessing',
            next: 'boxesToProccessing',
            previous: 'plateToBoxes',
            previousTitle: 'Plate',
        },
        boxesToProccessing: {
            type: 'animation',
            location: 'honey',
            time_start: 70.5,
            time_end: 78,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'processing',
        },
        processing: {
            description: 'In a commercial operation, the honey is scraped off the frames with an uncapping machine. The honey then drips into a hopper which begins moving honey along a process that helps separate it from the wax. The process includes spinning the frames in centrifugal machines called extractors and then letting honey settle in tanks to clarify further. When the honey is clear, it is pumped into storage barrels where it can be stored indefinitely without spoilage. Once barreled, the honey is ready to be shipped to chefs, bakers and for sale to retail consumers.',
            stepNumber: 2,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/honey-jpgs/honey-processing-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Honey/Honey+Processing.mp4',
            location: 'honey',
            nextTitle: 'Cooking',
            next: 'processingToCooking',
            previous: 'processingToCollecting',
            previousTitle: 'Collecting',
        },
        processingToCooking: {
            type: 'animation',
            location: 'honey',
            time_start: 90.5,
            time_end: 96,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'cooking',
        },
        cooking: {
            description: 'Honey is added to a hot frying pan. The heat is then turned down to medium and reduced until honey becomes a deep golden brown colour. Cracked black pepper and lemon zest are added. The roasted carrots are then tossed in the honey caramel and seasoned as needed.',
            stepNumber: 3,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/honey-jpgs/Honey-cooking-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Honey/Honey+Cooking.mp4',
            location: 'honey',
            next: 'btp',
            nextTitle: 'Back to Plate',
            previous: 'cookingToProcessing',
            previousTitle: 'Processing',
        },
        btp: {
            type: 'animation',
            location: 'beef',
            time_start: 240,
            time_end: 243,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp',
        }
    },
    beef: {
        numberOfStops: 4,
        intro: {
            action: 'intro',
            navButtons: [
                {type: 'btp', view: 'home', title:'Plate'},
                {type: 'animation', view: 'map', title:'Beef Tenderloin', location: 'beef', subSection: 'plateToCalving'},],
            internalButtons: [{}],
            location: 'beef',
            disableNavButtons: false,
            shouldLoop: false,
        },
        plateToCalving: {
            type: 'animation',
            location: 'beef',
            time_start: 20.5,
            time_end: 26,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'calving',
        },
        calvingToPlate: {
            type: 'animation',
            location: 'beef',
            time_start: 280,
            time_end: 284.5,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp',
        },
        calving: {
            description: ' Beef farmers have specially selected breeding cows that give birth to young calves on pasture. Theses calves are kept with their mothers for approximately 8 months, where they usually roam outdoors and drink her milk. As the calves grow, they begin weaning off their mother’s milk and eating grass, on an open pasture. This stage of production usually takes place on its own farm and is called a “cow calf” operation. After about 8 months, the now larger cattle are sold to another farm, called a feedlot.',
            stepNumber: 1,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/beef-jpgs/beef-calving-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Beef/Calving.mp4',
            location: 'beef',
            nextTitle: 'Feedlot',
            next: 'calvingToFeedLot',
            previous: 'calvingToPlate',
            previousTitle: 'Plate',
        },
        calvingToFeedLot: {
            type: 'animation',
            location: 'beef',
            time_start: 30.5,
            time_end: 37.5,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'feedlot',
        },
        feedlotToCalving: {
            type: 'animation',
            location: 'beef',
            time_start: 267,
            time_end: 274,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'calving',
        },
        feedlot: {
            description: ' Feedlots take in cattle from numerous cow calf operations and house them either in large barns or outdoors in pens. Feedlots are much larger than cow calf farms as they aggregate cattle from many cow calf operations. The cattle continue growing as they are fed a diet that varies from farm to farm, but usually includes a mixture of grains and forages, which contain balanced levels of energy and protein. The cattle reach the feedlot when they are about one year old and are sold usually sold before they reach 24 months. At this age, they are fully grown and sent for slaughter, weighing anywhere between 1,200 to 1,800 pounds. Towards the end of their lives, some cattle have specialized, lower energy diets that do not include grains. These are sometimes labeled grass finished and are usually sold for slaughter at 30 months of age.',
            stepNumber: 2,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/beef-jpgs/beef-feedlot-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Beef/Feedlot.mp4',
            location: 'beef',
            nextTitle: 'Abbatoir',
            next: 'feedlotToSlaughter',
            previous: 'feedlotToCalving',
            previousTitle: 'Calving',
        },
        feedlotToSlaughter: {
            type: 'animation',
            location: 'beef',
            time_start: 40.5,
            time_end: 45.5,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'slaughter',
        },
        slaughterToFeedlot: {
            type: 'animation',
            location: 'beef',
            time_start: 260,
            time_end: 265,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'feedlot',
        },
        slaughter: {
            description: 'The cattle are loaded onto well ventilated trailers that are designed to reduce the stress of the cattle while in transport and ensure safety. Once the cattle arrive at the processing facility, they are herded into a specially designed lane called a chute that helps keep the cattle calm during this stage. Modern slaughter techniques are used to ensure that the animal is unconscious immediately and feels no pain. Both of these stages have been carefully researched to ensure the most efficient and humane slaughter. People such as Temple Grandin were pioneers in this field and developed the current method. Butchers then cut each carcass into cuts of meat that consumers would recognize in a grocery store or at a restaurant.',
            stepNumber: 3,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/beef-jpgs/beef-slaughtery-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Beef/Abbatoir.mp4',
            location: 'beef',
            nextTitle: 'Cooking',
            next: 'slaughterToCooking',
            previous: 'slaughterToFeedlot',
            previousTitle: 'Feedlot'
        },
        slaughterToCooking: {
            type: 'animation',
            location: 'beef',
            time_start: 50,
            time_end: 56,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'cooking',
        },
        cookingToSlaughter: {
            type: 'animation',
            location: 'beef',
            time_start: 250,
            time_end: 255,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'slaughter',
        },
        cooking: {
            description: 'Before cooking the beef, the fat and silver skin is removed from the tenderloin. The whole roast is cut into 8 inch segments and then sliced lengthwise 3/4s of the way through, at which point pork lard is stuffed into the meat. The larded tenderloin is then tied together, before being pan seared until golden brown. Butter is then added to the pan and basted on the beef. The beef is then finished in the oven at 375 F and roasted for 10 minutes. The beef is then left to rest and sliced to serve.',
            stepNumber: 4,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/beef-jpgs/beef-cooking-finishedtif.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Beef/Beef+Cooking.mp4',
            location: 'beef',
            nextTitle: 'Back to Plate',
            next: 'btp',
            previous: 'cookingToSlaughter',
            previousTitle: 'Slaughtery',
        },
        btp: {
            type: 'animation',
            location: 'beef',
            time_start: 240,
            time_end: 243,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp',
        },
    },
    milk: {
        numberOfStops: 5,
        intro: {
            action: 'intro',
            navButtons: [
                {type: 'btp', view: 'home', title:'Plate'},
                {type: 'animation', view: 'map', title:'Bread Sauce', location: 'milk', subSection: 'plateToBarn'},],
            internalButtons: [{}],
            location: 'milk',
            disableNavButtons: false,
            shouldLoop: false,
        },
        plateToBarn: {
            type: 'animation',
            location: 'milk',
            time_start: 100.5,
            time_end: 106,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'barn',
        },
        barnToPlate: {
            type: 'animation',
            location: 'milk',
            time_start: 364,
            time_end: 370,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp',
        },
        barn: {
            description: ' When dairy calves are born, they spend a few hours with their mothers while they are licked off to stimulate blood flow. The mother cow’s milk (called colostrum) contains essential immunoglobulins, and is given to the calf within one hour to allow the calf to develop their own functioning immune system. Once the calf has been cleaned off it is then moved to calving hutches - individualized pens where the calves can more closely cared for and monitored. The mother cow will be carefully monitored and then return to the milking herd. Male (bull) calves are usually sent to other farms where they can be raised for veal or breeding purposes. Females (heifers) are kept and raised until they have their first calf at about two years of age to continue the dairy cycle.',
            stepNumber: 1,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/Milk-jpgs/Milk-Bran-Finished+.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Milk/Dairy+Barn.mp4',
            location: 'milk',
            nextTitle: 'Milking Parlour',
            next: 'barnToMilk',
            previous: 'barnToPlate',
            previousTitle: 'Plate',
        },
        barnToMilk: {
            type: 'animation',
            location: 'milk',
            time_start: 110.5,
            time_end: 117.5,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'milk'
        },
        milkToBarn: {
            type: 'animation',
            location: 'milk',
            time_start: 352,
            time_end: 360,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'barn'
        },
        milk: {
            description: 'On this farm, each of their 400 cows are milked three times per day to closely simulate the natural cycles of the cow and her calf. Each cow is identified in the computer by her leg band, to allow her daily production and other daily activities to be monitored. If the cow has an infection or is being treated with antibiotics, the milk cannot be kept and is immediately routed away to a separate tank and disposed of. This milking parlour (where cows are milked) milks 24 cows at a time. The 24 cows are milked and are then released back into the herd to sleep and eat for the rest of the day.',
            stepNumber: 2,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/Milk-jpgs/Milk-Milking+Parlour-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Milk/Milking+Parlour.mp4',
            location: 'milk',
            nextTitle: 'Milking truck',
            next: 'milkToTruck',
            previous: 'milkToBarn',
            previousTitle: 'barn',
        },
        milkToTruck: {
            type: 'animation',
            location: 'milk',
            time_start: 120,
            time_end: 125.5,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'truck'
        },
        truckToMilk: {
            type: 'animation',
            location: 'milk',
            time_start: 345,
            time_end: 350,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'milk'
        },
        truck: {
            description: 'This farm produces about 16,500 liters of milk per day, which is collected by a large tanker truck on a daily basis. The driver takes a sample which is tested in a lab for antibiotic residue, bacteria levels, somatic cell levels, fat, protein, other solids, and freezing point. Every farm in Canada is tested every single day. If any farm is caught with any trace amounts of antibiotics in the milk, the milk is disposed of and the farm is fined, even for a first offence. The truck will stop at other farms depending on the size and will then go to the dairy the same day for the milk to be processed.',
            stepNumber: 3,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/Milk-jpgs/Milk+Truck+-+Milk-finished-v2.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Milk/Milk+Truck.mp4',
            location: 'milk',
            nextTitle: 'Processing',
            next: 'truckToProcessing',
            previous: 'truckToMilk',
            previousTitle: 'Milking Parlour',
        },
        truckToProcessing: {
            type: 'animation',
            location: 'milk',
            time_start: 130,
            time_end: 136,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'processing'
        },
        processing: {
            description: 'The truck arrives at the processing plant and the milk is then tested once again for contaminants.  The milk is then offloaded and pasteurized for safety purposes. Essential vitamins are added to the milk and it is then processed into cream, skim and other dairy products such as ice cream and butter. Our dish contains buttermilk, which is specially processed by adding bacterial cultures, in order to give it a unique taste.',
            stepNumber: 4,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/Milk-jpgs/milk-processing-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Milk/Milk+Processing.mp4',
            location: 'milk',
            nextTitle: 'Cooking',
            next: 'proccessingToCooking',
            previous: 'truckToMilk',
            previousTitle: 'Milking Parlour',
        },
        proccessingToCooking: {
            type: 'animation',
            location: 'milk',
            time_start: 285,
            time_end: 293,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'cooking'
        },
        cooking: {
            description: 'The buttermilk is used to create a bread sauce to garnish our dish. The buttermilk is warmed very gently at a low temperature on the stove with equal parts buttermilk and regular milk. Spices are then added such as allspice, nutmeg, black peppercorn, cinnamon, bay leaf and clove. The mixture is then brought to 180 F and removed from heat to allow the ingredients to infuse for 20 mins. Once complete, the spices are strained off and the liquid is warmed once again. This spiced milk mixture is then blended with house made bread and blitzed until smooth.',
            stepNumber: 5,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/Milk-jpgs/+milk-Cooking-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Milk/Milk+Cooking.mp4',
            location: 'milk',
            nextTitle: 'Back to Plate',
            next: 'btp',
            previous: 'cookingToTruck',
            previousTitle: 'Milk Truck',
        },
        btp: {
            type: 'animation',
            location: 'milk',
            time_start: 240,
            time_end: 243,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp',
        },
    },
    potatoes: {
        numberOfStops: 4,
        intro: {
            action: 'intro',
            navButtons: [
                {type: 'btp', view: 'home', title:'Plate'},
                {type: 'animation', view: 'map', title:'Potato Tots', location: 'potatoes', subSection: 'plateToIrrigation'},],
            internalButtons: [{}],
            location: 'potatoes',
            disableNavButtons: false,
            shouldLoop: false
        },
        plateToIrrigation: {
            type: 'animation',
            location: 'potatoes',
            time_start: 145.5,
            time_end: 151,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'irrigation'
        },
        irrigationToPlate: {
            type: 'animation',
            location: 'potatoes',
            time_start: 435,
            time_end: 440,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp'
        },
        irrigation: {
            description: 'A potato seed is a small chunk of an existing potato which is cut into desirable size seed pieces. The pieces are then planted in the ground and partially covered with soil. After a couple of weeks, the sprouting seed begins to crack through the soil surface. At that point, the potatoes are “hilled” to have ample amount of soil for the new developing potatoes to grow and be protected from the sun and elements.',
            stepNumber: 1,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/potato-jpgs/potato-planting-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Potatoe/Potatoe+Planting.mp4',
            location: 'potatoes',
            nextTitle: 'Harvesting',
            next: 'irrigationToHarvest',
            previous: 'irrigationToPlate',
            previousTitle: 'Plate',
        },
        irrigationToHarvest: {
            type: 'animation',
            location: 'potatoes',
            time_start: 157,
            time_end: 163,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'harvest'
        },
        harvestToIrrigation: {
            type: 'animation',
            location: 'potatoes',
            time_start: 395,
            time_end: 400,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'harvest'
        },
        harvest: {
            description: 'When the potatoes have grown to the desired size, the potatoes are then dug out of the ground with a mechanical harvester. The process of digging includes removing dead vines and undesirable potatoes.',
            stepNumber: 2,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/potato-jpgs/potato-harvest-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Potatoe/Potatoe+Harvest.mp4',
            location: 'potatoes',
            nextTitle: 'Processing',
            next: 'harvestToProcessing',
            previous: 'harvestToIrrigation',
            previousTitle: 'Irrigation',
        },
        harvestToProcessing: {
            type: 'animation',
            location: 'potatoes',
            time_start: 164,
            time_end: 170,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'processing',
        },
        proccessingToHarvest: {
            type: 'animation',
            location: 'potatoes',
            time_start: 390,
            time_end: 495,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'processing',
        },
        processing: {
            description: 'The potatoes are then transported to a facility where they are sized to the desired specs of the customer. The Potatoes are shipped to the pack house to be washed and regraded for packing. Various packing is used depending on the type and size of the potatoes and is determined by the end users.',
            stepNumber: 3,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/potato-jpgs/potatoes-planting-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Potatoe/Potatoe+Process.mp4',
            location: 'potatoes',
            nextTitle: 'Cooking',
            next: 'processingToCooking',
            previous: 'proccessingToHarvest',
            previousTitle: 'Harvesting'
        },
        processingToCooking: {
            type: 'animation',
            location: 'potatoes',
            time_start: 174,
            time_end: 180,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'cooking'
        },
        cookingToProcessing: {
            type: 'animation',
            location: 'potatoes',
            time_start: 380,
            time_end: 385,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'cooking'
        },
        cooking: {
            description: 'Potatoes are peeled and run through a food processor to make small pieces.  Next, the chopped potatoes are rinsed and spread on a tray and baked at 300F until the moisture is gone and potato is semi soft. They are then dusted with powdered gelatin, and rolled into tubes, cut and fried until golden brown.',
            stepNumber: 4,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/potato-jpgs/potato-cooking-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Potatoe/Potatoe+Cooking.mp4',
            location: 'potatoes',
            nextTitle: 'Back to Plate',
            next: 'btp',
            previous: 'cookingToProcessing',
            previousTitle: 'Processing',
        },
        btp: {
            type: 'animation',
            location: 'beef',
            time_start: 240,
            time_end: 243,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp',
        },
    },
    sunflowers: {
        numberOfStops: 5,
        intro: {
            action: 'intro',
            navButtons: [
                {type: 'btp', view: 'home', title:'Plate'},
                {type: 'animation', view: 'map', title:'Sunflower Oil', location: 'sunflowers', subSection: 'plateToPlanting'},
            ],
            internalButtons: [{}],
            location: 'sunflowers',
            disableNavButtons: false,
            shouldLoop: false
        },
        plateToPlanting: {
            type: 'animation',
            location: 'sunflowers',
            time_start: 190.5,
            time_end: 196,
            shouldLoop: false,
            onComplete: ({location: 'sunflowers', subSection: 'plateToPlanting'}),
            nextStop: 'planting',
        },
        planting: {
            description: ' Sunflowers are planted in early spring using a similar planter to other crops. The planter is towed behind a tractor and plants many rows of seed at a time. The planter also puts a precise amount of fertilizer with each seed to help the plant kickstart its growth.',
            stepNumber: 1,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/sunflowers-jpgs/sunflower-planting-finished-v2.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Sunflower/Sunflower+Planting.mp4',
            location: 'sunflowers',
            nextTitle: 'Blooming',
            next: 'plantingToBlooming',
            previous: 'plantingToPlate',
            previousTitle: 'Plate',
        },
        plantingToBlooming: {
            type: 'animation',
            location: 'sunflowers',
            time_start: 200,
            time_end: 208,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'blooming',
        },
        blooming: {
            description: 'In mid-July the sunflowers are in full bloom and look like the flowers we all know and recognize. They are then left until late fall to dry and be harvested.',
            stepNumber: 2,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/sunflowers-jpgs/sunflower-bloming-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Sunflower/Sunflower+Blooming.mp4',
            location: 'sunflowers',
            nextTitle: 'Harvesting',
            next: 'bloomingToHarvest',
            previous: 'bloomingToPlanting',
            previousTitle: 'Planting',
        },
        bloomingToHarvest: {
            type: 'animation',
            location: 'sunflowers',
            time_start: 209.5,
            time_end: 215.5,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'harvest',
        },
        harvest: {
            description: 'Once the sunflowers have dried up, they are harvested with a combine harvester, much like corn and wheat. The harvester chops the plants and strips the seed off of the flowers. It then stores the seed in a large hopper on top of the machine, to be later off loaded into large wagons and stored in silos. The rest of the plant is chopped and spread back onto the field to decompose and redeposit nutrients in the soil.',
            stepNumber: 3,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/sunflowers-jpgs/sunflower-harvest-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Sunflower/Sunflower+Harvest.mp4',
            location: 'sunflowers',
            nextTitle: 'Processing',
            next: 'harvestToProcessing',
            previous: 'harvestToBlooming',
            previousTitle: 'Blooming',
        },
        harvestToProcessing: {
            type: 'animation',
            location: 'sunflowers',
            time_start: 220,
            time_end: 226,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'processing',
        },
        processing: {
            description: ' After the wagons have been transported to the processing plant, the seeds are offloaded. The seeds from the silo are then transferred into the processing plant where they are separated from the shell and cleaned of any impurities such as seeds from weeds in the field. The seeds then enter a press that extracts the oil out of the sunflower seed.',
            stepNumber: 4,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/sunflowers-jpgs/sunflower-processing-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Sunflower/Sunflower+Processing.mp4',
            location: 'sunflowers',
            nextTitle: 'Cooking',
            next: 'processingToCooking',
            previous: 'cookingToHarvest',
            previousTitle: 'Harvesting',
        },
        processingToCooking: {
            type: 'animation',
            location: 'sunflowers',
            time_start: 229,
            time_end: 238,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'cooking',
        },
        cooking: {
            description: 'Sunflower oil is a great substitute for vegetable oil when baking bread. First, yeast and sugar are added to water. Then, flour as well as the sunflower oil are added. Next, a baking pan is rubbed with sunflower oil and the mix is added into a baking pan. Once the bread has baked, it is then cut into small cubes and blended in with the dairy to create the bread sauce. A little drizzle of sunflower oil over the plate when finished helps bring all the flavors together.',
            stepNumber: 5,
            backgroundImage: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/slider-titles/sunflowers-jpgs/sunflower-cooking-finished.jpg',
            videoUrl: 'https://s3-us-west-2.amazonaws.com/before-the-lottie-video-storage/Videos/Sunflower/Sunflower+Cooking.mp4',
            location: 'sunflowers',
            nextTitle: 'Back to Plate',
            next: 'btp',
            previous: 'cookingToHarvest',
            previousTitle: 'Harvesting',
        },
        btp: {
            type: 'animation',
            location: 'sunflowers',
            time_start: 240,
            time_end: 243,
            shouldLoop: false,
            onComplete: true,
            nextStop: 'btp',
        },
    }
};
